# Generated by Django 5.2.1 on 2025-05-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_calories",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=8),
                ),
                (
                    "target_protein",
                    models.DecimalField(decimal_places=2, default=150, max_digits=8),
                ),
                (
                    "target_carbs",
                    models.DecimalField(decimal_places=2, default=250, max_digits=8),
                ),
                (
                    "target_fat",
                    models.DecimalField(decimal_places=2, default=65, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "calories_per_100g",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "protein_per_100g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "carbs_per_100g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fat_per_100g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CalorieEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_grams", models.DecimalField(decimal_places=2, max_digits=8)),
                ("calories", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "protein",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "carbs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("fat", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        default="snack",
                        max_length=20,
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_tracking.fooditem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
